import React from "react";
import { useEffect } from "react";
import {useState} from 'react';

import { useRouter } from "next/router";
import Nav from '../../components/Nav/Nav'
import Head from "next/head";
import { cats } from "../../data";



export default function Cat() {

const [cat, setCat] = useState(null);



  const router = useRouter();
  const { id } = router.query;

  const fetchCat = async () => {
    const response = await fetch(`/api/cats/${id}`);
    const data = await response.json();
    setCat(data);
  };

  useEffect(() => {
    fetchCat();
  }, []);

  return (
    <>
      
      <Head>
        <title>{cats.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

    
    <div>
    <Nav/>
      {cat && (
        <div className="container mt-5 flex" style={{display: "flex", height:"23rem" }}>
          <img src={cat.image.url} alt={cat.image.alt} />
          <div className="mx-5">
            <h1 className="container mt-5 flex" style={{display: "flex", height:"5rem" }}>{cat.name}</h1>
            <h1 >{cat.description}</h1>
          </div>
        </div>
      )}
    </div>

    </>
  );
}
