
import Head from "next/head";
import React, { useState, useEffect } from "react";
import Card from "../../components/Card/Card";
import DefaultLayout from "../../layouts/Default";

// https://www.youtube.com/watch?v=6HTs8HtZMt0&t=978s link for this tutorial

export default function index() {
  const [cats, setCats] = useState([]);

  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    const data = await response.json();
    console.log(data);
    setCats(data);
  };

  useEffect(() => {
    fetchCats();
  }, []);

 
  return (
    <>
     <Head>
        <title>Our Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
  <DefaultLayout>
      <div className="container mt-5">
        <div style={{ display: "flex", flexWrap: "wrap" }}>
          {cats.map((cat) => (
            <Card
              name={cat.name}
              id={cat.id}
              phone={cat.phone}
              email={cat.email}
              image={cat.image}
            />
          ))}
        </div>
      </div>
      </DefaultLayout>
    </>
  );
}
