import Head from "next/head";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav/Nav";
import Jumbotron from "../components/Jumbotron/Jumbotron";
import DefaultLayout from "../layouts/Default";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cats world!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* 
      you can use different favicon,titles, dest etc. for different pages! */}
      </Head>

      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </div>
  );
}
